import assert from 'node:assert/strict';
import { stageFixture, FakeElement } from './stage-test-fixture.mjs';
let checks=0;
async function check(name,run){await run();checks++;console.log('PASS '+name);}
await check('fresh home visit with restored scroll starts at the room', async()=>{const f=stageFixture({scroll:6300});await f.load();assert.equal(f.state().progress,0);assert.equal(f.globals.scrollY,0);assert.equal(f.state().playing,true);f.cleanup();});
await check('restoration scroll while images load cannot fast-forward intro',async()=>{const f=stageFixture();f.globals.scrollY=6300;f.window.emit('scroll');await f.load();assert.equal(f.state().progress,0);assert.equal(f.state().playing,true);f.cleanup();});
await check('late programmatic scroll events cannot stop active autoplay',async()=>{const f=stageFixture();await f.load();f.frame(1000);const p=f.state().progress;f.globals.scrollY+=40;f.window.emit('scroll');assert.equal(f.state().progress,p);assert.equal(f.state().playing,true);f.cleanup();});
await check('input on content cannot accelerate opening',async()=>{const f=stageFixture();await f.load();const content=new FakeElement();content.closest=selector=>selector.includes('[data-content-interaction]')?content:null;f.click(content);assert.equal(f.state().playbackRate,1);f.cleanup();});
await check('each intro click doubles rate without a visible hint, capped at8x',async()=>{const f=stageFixture();await f.load();for(const expected of [2,4,8,8]){f.click();assert.equal(f.state().playbackRate,expected);assert.equal(f.get('#film-hint').hidden,true);}f.cleanup();});
await check('manual wheel still takes control once visible',async()=>{const f=stageFixture();await f.load();f.frame(1000);f.window.emit('wheel');f.globals.scrollY=2000;f.window.emit('scroll');assert.equal(f.state().playing,false);assert.equal(f.state().progress,2000/7100);f.cleanup();});
console.log(checks+' intro refinement checks passed.');
const visibility = stageFixture();await visibility.load();visibility.frame(2500);const suspended=visibility.state().progress;visibility.document.hidden=true;visibility.document.emit('visibilitychange');visibility.frame(9000);visibility.document.hidden=false;visibility.document.emit('visibilitychange');assert.equal(visibility.state().playing,true,'Visible intro resumes after tab was hidden');assert.equal(visibility.state().progress,suspended);visibility.frame(10000);assert.ok(Math.abs(visibility.state().progress-(suspended+1/14))<.000001);visibility.cleanup();console.log('PASS visibility resumes with rebased clock');
const resize=stageFixture();await resize.load();resize.frame(2500);resize.window.emit('resize');assert.equal(resize.state().playing,true,'Resize preserves running intro');resize.cleanup();console.log('PASS resize continues intro');
const clickResume=stageFixture();await clickResume.load();clickResume.frame(3000);clickResume.window.emit('wheel');const held=clickResume.state().progress;clickResume.click();assert.equal(clickResume.state().playing,true,'Click resumes manually paused city view');assert.equal(clickResume.state().playbackRate,2);assert.equal(clickResume.state().progress,held);clickResume.cleanup();console.log('PASS click resumes a manually paused intro at the same frame');
